# Unique name for this workflow
name: Packaging

# Definition when the workflow should run
on:
  release:
    types: [released]

# Jobs to be executed
jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      # Checkout the code in the pull request
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          ref: 'main'

      # Store secret for dev hub
      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

      # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'

      # Remove auth file
      - name: Remove auth file
        run: rm -f ./DEVHUB_SFDX_URL.txt

      # Add namespace to project config
      - name: Add namespace to project config
        run: |
          sed -i 's,"namespace": "","namespace": "LabsActionPlans",' sfdx-project.json

      # Update release number in sfdx-project.json
      - name: Update Package number in sfdx-project.json
        run: |
          versionNumber="${{ github.event.release.tag_name }}"
          versionName="${{ github.event.release.name }}"
          versionNameRegex="\"versionName\": \".*\""
          versionNumberRegex="\"versionNumber\": \"[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.NEXT\""
          newVersionName="\"versionName\": \"${versionName}\""
          newVersionNumber="\"versionNumber\": \"${versionNumber/v/}.NEXT\""
          sed -i -E "s,${versionNameRegex},${newVersionName}," sfdx-project.json
          sed -i -E "s,${versionNumberRegex},${newVersionNumber}," sfdx-project.json

      # Create package version and extract its id
      - name: Create package version
        id: create-package-version
        run: |
          set +e
          json=$(sfdx force:package:version:create -c -p ActionPlans --path sfdx-source/LabsActionPlans --installationkeybypass -w 20 --json)
          echo $json
          status=$(echo $json | jq '.status')
          if [ $status == "0" ]; then
              packageVersionId=$(echo $json | jq '.result.SubscriberPackageVersionId')
              echo "::set-output name=packageVersionId::$packageVersionId"
          else
              echo "sfdx force:package:version:create failed"
          fi
          exit $status

      Update sfdx-project.json and README to use only latest package version
      - name: 'Update sfdx-project.json and README'
        id: packaging-updater
        uses: trailheadapps/github-action-sfdx-packaging-updater@main

      # Remove namespace from project config
      - name: Remove namespace from project config
        run: |
          sed -i 's,"namespace": "LabsActionPlans","namespace": "",' sfdx-project.json

      # Update sfdx-project.json
      - name: 'Commit changes'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Created new package version'
          file_pattern: sfdx-project.json README.md
